spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: tool-inventory-service
              uri: lb://tool-inventory-service
              predicates:
                - Path=/tool-inventory-service/**

server:
  port: 8080

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/